sudo: required
services:
  - docker

before_install:
  - docker build -t jcmunday/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jcmunday/react-test npm test

after_success:
  - docker build -t jcmunday/multi-client ./client
  - docker build -t jcmunday/multi-nginx ./nginx
  - docker build -t jcmunday/multi-server ./server
  - docker build -t jcmunday/multi-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jcmunday/multi-client
  - docker push jcmunday/multi-nginx
  - docker push jcmunday/multi-server
  - docker push jcmunday/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react-multi'
  env: 'Dockerreactmulti-env'
  bucket_name: 'elasticbeanstalk-us-east-2-642912332160'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
